/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewMedico;

import Verificar.Verificacao;
import controllerDAO.MedicoDAO;

import model.Medico;

/**
 *
 * @author Anderson
 */
public class CadastroMedico extends javax.swing.JFrame {
    String let;

    /**
     * Creates new form CadastroAluno
     */
    public CadastroMedico() {
        initComponents();
        lisEstados();
    }
    
     public void lisEstados(){
        
        jComboBox_estados.removeAllItems();
        
         jComboBox_estados.addItem("Acre");
         jComboBox_estados.addItem("Alagoas");
         jComboBox_estados.addItem("Alagoas"+"Amapá");
         jComboBox_estados.addItem("Amapá");
         jComboBox_estados.addItem("Amazonas");
         jComboBox_estados.addItem("Bahia");
         jComboBox_estados.addItem("Ceará");
         jComboBox_estados.addItem("Distrito Federal");
         jComboBox_estados.addItem("Espírito Santo");
         jComboBox_estados.addItem("Goiás");
         jComboBox_estados.addItem("Maranhão");
         jComboBox_estados.addItem("Mato Grosso");
         jComboBox_estados.addItem("Mato Grosso do Sul");
         jComboBox_estados.addItem("Minas Gerais");
         jComboBox_estados.addItem("Paraíba");
         jComboBox_estados.addItem("Paraná");
         jComboBox_estados.addItem("Pernambuco");
         jComboBox_estados.addItem("Piauí");
         jComboBox_estados.addItem("Rio de Janeiro");
         jComboBox_estados.addItem("Rio Grande do Norte");
         jComboBox_estados.addItem("Rio Grande do Sul");
         jComboBox_estados.addItem("Rondônia");
         jComboBox_estados.addItem("Roraima");
         jComboBox_estados.addItem("Santa Catarina");
         jComboBox_estados.addItem("São Paulo");
         jComboBox_estados.addItem("Sergipe");
         jComboBox_estados.addItem("Tocantins");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtCRM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jButton_ir_menu = new javax.swing.JButton();
        lblMensagem10 = new javax.swing.JLabel();
        jTextField_bairro = new javax.swing.JTextField();
        lblMensagem12 = new javax.swing.JLabel();
        lblMensagem4 = new javax.swing.JLabel();
        jTextField_cidade = new javax.swing.JTextField();
        lblMensagem11 = new javax.swing.JLabel();
        jComboBox_estados = new javax.swing.JComboBox();
        jText_tele1 = new javax.swing.JTextField();
        lblMensagem13 = new javax.swing.JLabel();
        jText_tele2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblMensagem14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_numero = new javax.swing.JTextField();
        jTextField_rua = new javax.swing.JTextField();
        lblMensagem9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Medico");

        jLabel2.setText("CRM");

        jLabel3.setText("Nome");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jButton_ir_menu.setText("< voltar");
        jButton_ir_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ir_menuActionPerformed(evt);
            }
        });

        lblMensagem10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem10.setText("Rua:");

        lblMensagem12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem12.setText("Bairro:");

        lblMensagem4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem4.setText("Estado:");

        lblMensagem11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem11.setText("Cidade:");

        jComboBox_estados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_estadosActionPerformed(evt);
            }
        });

        jText_tele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_tele1ActionPerformed(evt);
            }
        });

        lblMensagem13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem13.setText("Numero tel(1):");

        jText_tele2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_tele2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel4.setText("Contato");

        lblMensagem14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem14.setText("Numero tel(2):");

        jLabel7.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel7.setText("Endereço");

        jTextField_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroActionPerformed(evt);
            }
        });

        jTextField_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ruaActionPerformed(evt);
            }
        });

        lblMensagem9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem9.setText("Numero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ir_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCadastrar))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMensagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblMensagem10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(lblMensagem12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextField_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMensagem11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170)
                                .addComponent(lblMensagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(jComboBox_estados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblMensagem13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblMensagem14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jText_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jText_tele2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(jtCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem9)
                    .addComponent(lblMensagem10)
                    .addComponent(lblMensagem12))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem11)
                    .addComponent(lblMensagem4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem13)
                    .addComponent(lblMensagem14))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_tele2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jButton_ir_menu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        
        Medico medico = new Medico();
    
        Verificacao Verif = new Verificacao();
        
        Verif.erro=0;
         
        let = jtNome.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
        
        let = jtCRM.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
        let = jText_tele1.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
        let = jText_tele2.getText();
        Verif.verif_vazio(let);
        
        let = jTextField_numero.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
        let = jTextField_rua.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
        
        let = jTextField_bairro.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
        
        let = jTextField_cidade.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
        
  
        if(Verif.erro==0){
        medico.setCrm(Integer.parseInt(jtCRM.getText()));
        medico.setNome(jtNome.getText());
        
        medico.setTel_1(jText_tele1.getText());
        medico.setTel_2(jText_tele2.getText()); 
        
        medico.setEndere_numero(jTextField_numero.getText());
        medico.setRua(jTextField_rua.getText());
        medico.setBairro(jTextField_bairro.getText());
        medico.setCidade(jTextField_cidade.getText());
        medico.setEstado(String.valueOf(jComboBox_estados.getSelectedItem()));
        
        MedicoDAO crudMedico = new MedicoDAO();
        
        crudMedico.salvarMedico(medico);
       
        
        
        
         jtCRM.setText("");
         jtNome.setText("");
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jButton_ir_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ir_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_ir_menuActionPerformed

    private void jComboBox_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_estadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_estadosActionPerformed

    private void jText_tele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_tele1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_tele1ActionPerformed

    private void jText_tele2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_tele2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_tele2ActionPerformed

    private void jTextField_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numeroActionPerformed

    private void jTextField_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ruaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ir_menu;
    private javax.swing.JComboBox jComboBox_estados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField_bairro;
    private javax.swing.JTextField jTextField_cidade;
    private javax.swing.JTextField jTextField_numero;
    private javax.swing.JTextField jTextField_rua;
    private javax.swing.JTextField jText_tele1;
    private javax.swing.JTextField jText_tele2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JTextField jtCRM;
    private javax.swing.JTextField jtNome;
    private javax.swing.JLabel lblMensagem10;
    private javax.swing.JLabel lblMensagem11;
    private javax.swing.JLabel lblMensagem12;
    private javax.swing.JLabel lblMensagem13;
    private javax.swing.JLabel lblMensagem14;
    private javax.swing.JLabel lblMensagem4;
    private javax.swing.JLabel lblMensagem9;
    // End of variables declaration//GEN-END:variables
}
