/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewPaciente;

import Verificar.Verificacao;
import viewMedico.*;
import controllerDAO.MedicoDAO;
import controllerDAO.PacienteDAO;
import model.Medico;
import model.Paciente;
import model.Pessoa;

/**
 *
 * @author Anderson
 */
public class CadastroPaciente extends javax.swing.JFrame {
    
    
   

    /**
     * Creates new form CadastroAluno
     */
    public CadastroPaciente() {
        initComponents();
        lisEstados();
        listAno1();
        listMes();
        listDias();
    }
    
     public void listAno1(){
         jComboBox_ano.removeAllItems();
      
        int ano = 1899;
          while(ano<2019){
            ano=ano+1;
            jComboBox_ano.addItem(ano);
            
        }
        
    }
    
   public void listMes(){
       
       int mes =0;
        jComboBox_mes.removeAllItems();
        
          while(mes<9){
            mes=mes+1;
            jComboBox_mes.addItem("0"+mes);
            
        }
                   
        while(mes<12){
            mes=mes+1;
            jComboBox_mes.addItem(mes);
            
        }
  
   }
    
    public void listDias(){
        int dia =0;
        jComboBox_dia.removeAllItems();
                   
        while(dia<31){
            dia=dia+1;
            jComboBox_dia.addItem(dia);
            
        }
    }
   
    
    public void lisEstados(){
        
        jComboBox_estados.removeAllItems();
        
         jComboBox_estados.addItem("Acre");
         jComboBox_estados.addItem("Alagoas");
         jComboBox_estados.addItem("Alagoas"+"Amapá");
         jComboBox_estados.addItem("Amapá");
         jComboBox_estados.addItem("Amazonas");
         jComboBox_estados.addItem("Bahia");
         jComboBox_estados.addItem("Ceará");
         jComboBox_estados.addItem("Distrito Federal");
         jComboBox_estados.addItem("Espírito Santo");
         jComboBox_estados.addItem("Goiás");
         jComboBox_estados.addItem("Maranhão");
         jComboBox_estados.addItem("Mato Grosso");
         jComboBox_estados.addItem("Mato Grosso do Sul");
         jComboBox_estados.addItem("Minas Gerais");
         jComboBox_estados.addItem("Paraíba");
         jComboBox_estados.addItem("Paraná");
         jComboBox_estados.addItem("Pernambuco");
         jComboBox_estados.addItem("Piauí");
         jComboBox_estados.addItem("Rio de Janeiro");
         jComboBox_estados.addItem("Rio Grande do Norte");
         jComboBox_estados.addItem("Rio Grande do Sul");
         jComboBox_estados.addItem("Rondônia");
         jComboBox_estados.addItem("Roraima");
         jComboBox_estados.addItem("Santa Catarina");
         jComboBox_estados.addItem("São Paulo");
         jComboBox_estados.addItem("Sergipe");
         jComboBox_estados.addItem("Tocantins");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jButton_ir_menu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_numero = new javax.swing.JTextField();
        jTextField_rua = new javax.swing.JTextField();
        lblMensagem9 = new javax.swing.JLabel();
        lblMensagem10 = new javax.swing.JLabel();
        jTextField_bairro = new javax.swing.JTextField();
        lblMensagem12 = new javax.swing.JLabel();
        lblMensagem4 = new javax.swing.JLabel();
        jTextField_cidade = new javax.swing.JTextField();
        lblMensagem11 = new javax.swing.JLabel();
        jComboBox_estados = new javax.swing.JComboBox();
        jText_Paci_tele1 = new javax.swing.JTextField();
        lblMensagem13 = new javax.swing.JLabel();
        jText_Paci_tele2 = new javax.swing.JTextField();
        lblMensagem14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCpf_cont = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_mes = new javax.swing.JComboBox();
        jComboBox_dia = new javax.swing.JComboBox();
        jComboBox_ano = new javax.swing.JComboBox();
        lblMensagem5 = new javax.swing.JLabel();
        lblMensagem6 = new javax.swing.JLabel();
        lblMensagem7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel1.setText("Contato");

        jLabel2.setText("CPF");

        jLabel3.setText("Nome");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jButton_ir_menu.setText("< voltar");
        jButton_ir_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ir_menuActionPerformed(evt);
            }
        });

        jLabel4.setText("Idade");

        jTextField_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroActionPerformed(evt);
            }
        });

        jTextField_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ruaActionPerformed(evt);
            }
        });

        lblMensagem9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem9.setText("Numero:");

        lblMensagem10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem10.setText("Rua:");

        lblMensagem12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem12.setText("Bairro:");

        lblMensagem4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem4.setText("Estado:");

        lblMensagem11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem11.setText("Cidade:");

        jComboBox_estados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_estadosActionPerformed(evt);
            }
        });

        jText_Paci_tele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Paci_tele1ActionPerformed(evt);
            }
        });

        lblMensagem13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem13.setText("Numero tel(1):");

        jText_Paci_tele2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Paci_tele2ActionPerformed(evt);
            }
        });

        lblMensagem14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem14.setText("Numero tel(2):");

        jLabel5.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel5.setText("Cadastro de paciente");

        jLabel6.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel6.setText("Dados pesoais");

        jLabel7.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel7.setText("Endereço");

        txtCpf_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpf_contActionPerformed(evt);
            }
        });

        jLabel8.setText(" -");

        jComboBox_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_mesActionPerformed(evt);
            }
        });

        jComboBox_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_diaActionPerformed(evt);
            }
        });

        jComboBox_ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_anoActionPerformed(evt);
            }
        });

        lblMensagem5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem5.setText("Mes");

        lblMensagem6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem6.setText("Ano");

        lblMensagem7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem7.setText("Dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jComboBox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMensagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(lblMensagem5)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMensagem6)
                                    .addComponent(jComboBox_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf_cont, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel3)
                                .addGap(13, 13, 13)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblMensagem13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblMensagem14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jText_Paci_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jText_Paci_tele2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_ir_menu)
                        .addGap(189, 189, 189)
                        .addComponent(jbCadastrar)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblMensagem10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblMensagem12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensagem11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(lblMensagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jComboBox_estados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpf_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jLabel3)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMensagem5)
                        .addComponent(lblMensagem6)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem9)
                    .addComponent(lblMensagem10)
                    .addComponent(lblMensagem12))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem11)
                    .addComponent(lblMensagem4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem13)
                    .addComponent(lblMensagem14))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText_Paci_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_Paci_tele2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ir_menu)
                    .addComponent(jbCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        
        String let;
        String cpf;
      
        Paciente paci = new Paciente();
        
      
        Verificacao Verif = new Verificacao();
       
        
        Verif.erro=0;
        
        let = jtCPF.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
          let = txtCpf_cont.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
        cpf=(jtCPF.getText()+txtCpf_cont.getText());
        Verif.verifCPF(cpf);
        
        let = jtNome.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
        
   
        
        let = jText_Paci_tele1.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
        let = jText_Paci_tele2.getText();
        Verif.verif_vazio(let);
        
        let = jTextField_numero.getText();
        Verif.verif_num(let);
        Verif.verif_nulo(let);
        
        let = jTextField_rua.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
        
        let = jTextField_cidade.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
      
        let = jTextField_bairro.getText();
        Verif.verif_let(let);
        Verif.verif_nulo(let);
  
        
        if(Verif.erro==0){
            
        paci.setCadas_CPF((jtCPF.getText())+txtCpf_cont.getText());
        paci.setCadas_nome(jtNome.getText());
        String data = (String.valueOf (jComboBox_dia.getSelectedItem()+"/"+jComboBox_mes.getSelectedItem()+"/"+jComboBox_ano.getSelectedItem()) );
        paci.setCadas_Idade(data);
        
        paci.setTel_1(jText_Paci_tele1.getText());
        paci.setTel_2(jText_Paci_tele2.getText()); 
        
        paci.setEndere_numero(jTextField_numero.getText());
        paci.setRua(jTextField_rua.getText());
        paci.setBairro(jTextField_bairro.getText());
        paci.setCidade(jTextField_cidade.getText());
        paci.setEstado(String.valueOf(jComboBox_estados.getSelectedItem()));
        
        PacienteDAO crudPaciente = new PacienteDAO();
        crudPaciente.salvarPaciente(paci);
         
       
        
        
         jtCPF.setText("");
         jtNome.setText("");
       
         jText_Paci_tele1.setText("");
         jText_Paci_tele2.setText("");
         jTextField_numero.setText("");
         jTextField_rua.setText("");
         jTextField_bairro.setText("");
         jTextField_cidade.setText("");
         txtCpf_cont.setText("");
        } else{
            
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jButton_ir_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ir_menuActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton_ir_menuActionPerformed

    private void jTextField_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numeroActionPerformed

    private void jTextField_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ruaActionPerformed

    private void jComboBox_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_estadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_estadosActionPerformed

    private void jText_Paci_tele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Paci_tele1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Paci_tele1ActionPerformed

    private void jText_Paci_tele2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Paci_tele2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Paci_tele2ActionPerformed

    private void txtCpf_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpf_contActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpf_contActionPerformed

    private void jComboBox_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_mesActionPerformed

    private void jComboBox_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_diaActionPerformed

    private void jComboBox_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_anoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ir_menu;
    private javax.swing.JComboBox jComboBox_ano;
    private javax.swing.JComboBox jComboBox_dia;
    private javax.swing.JComboBox jComboBox_estados;
    private javax.swing.JComboBox jComboBox_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField_bairro;
    private javax.swing.JTextField jTextField_cidade;
    private javax.swing.JTextField jTextField_numero;
    private javax.swing.JTextField jTextField_rua;
    private javax.swing.JTextField jText_Paci_tele1;
    private javax.swing.JTextField jText_Paci_tele2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtNome;
    private javax.swing.JLabel lblMensagem10;
    private javax.swing.JLabel lblMensagem11;
    private javax.swing.JLabel lblMensagem12;
    private javax.swing.JLabel lblMensagem13;
    private javax.swing.JLabel lblMensagem14;
    private javax.swing.JLabel lblMensagem4;
    private javax.swing.JLabel lblMensagem5;
    private javax.swing.JLabel lblMensagem6;
    private javax.swing.JLabel lblMensagem7;
    private javax.swing.JLabel lblMensagem9;
    private javax.swing.JTextField txtCpf_cont;
    // End of variables declaration//GEN-END:variables
}
